first set of mods for python3
hep-gc/shoal pull request #151
Opened 2020-01-30 22:44 UTC by rseuster

probably more modifications coming, with this the RPM at least builds OK

2021-01-11 20:24 UTC, MarcusEbert requested changes

2021-01-11 20:24 UTC, MarcusEbert commented on shoal-server/setup.py
> +        print ("Couldn't use either setuputils or distutils. Install one of those.")
setuputils -> setuptools

2021-01-11 20:24 UTC, MarcusEbert commented on shoal-server/shoal_server/config.py
>  log_file = '/var/log/shoal_server.log'
should be an option in the config file

2021-01-11 20:24 UTC, MarcusEbert commented on shoal-server/shoal_server/config.py
> +logging_level = 'WARNING'
should also be defined in the config file

2021-01-11 20:24 UTC, MarcusEbert commented on shoal-server/shoal_server/config.py
>  elif exists(abspath(homedir + "/.shoal/shoal_server.conf")):
should be second choice; local dir -> home dir -> system dir

2021-01-11 20:24 UTC, MarcusEbert commented on shoal-server/shoal_server/shoal.py
> +            logger.error(
"Recived message from %s  %s seconds in the future.",
￼                public_ip, (-1*(curr-time_sent)))

2021-01-11 20:24 UTC, MarcusEbert commented on shoal-server/shoal_server/shoal.py
> +level = logging.getLevelName(config.logging_level)
Here it gets the logging level which is fine (should come from config file), however in other parts of the code, the level is hardcoded to warning. Would be good to use everywhere the config value.

2021-01-11 20:24 UTC, MarcusEbert commented on shoal-server/shoal_server/utilities.py
> +#    name = socket.getfqdn(temp_ip)
remove old unused code

2021-01-12 20:46 UTC, colsond requested changes

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/config.py
> +logging_level = 'WARNING'
This is the hard coded default that will later be overwritten by the content of shoal_server.conf if it is set there.

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/shoal.py
> +level = logging.getLevelName(config.logging_level)
This function converts the loglevel string (ie INFO) to a numeric value (ie 20) or vise versa, we then use this level variable below to set the log level. The only place i've seen warning hard coded is the default config value in config.py.

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/shoal.py
> +            for squid_key in list(web.shoal):
Make a list of the shoal keys to loop over so you dont get data manipulation errors.

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/utilities.py
> +level = logging.getLevelName(config.logging_level)
this statement is probably superfluous, you can instead pass config.logging_level directly to setLevel.

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/utilities.py
> +        print ("no geolocation")
update prints to log statements. This particular statement could be level debug. Maybe update the message to include IP ("No geolocation for %s" % ip).

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/utilities.py
> +    except:
Catch and log this exception so its easier for an administrator to troubleshoot.

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/utilities.py
> +        logger.error("Could not compare the domain for the two ips")
Add IPs to log statement requestip: %s and squid_ip: %s

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/utilities.py
> +                logger.info("Next...")
this can be a debug level message

2021-01-12 20:46 UTC, colsond commented on shoal-server/shoal_server/utilities.py
>          else:
Nothing will fall into this else statement so it can be removed.

2021-01-12 21:09 UTC, MarcusEbert commented on shoal-server/shoal_server/shoal.py
> +            logger.warning('GeoLiteCity database needs manually updating.')
GeoLiteCity db is still used to make the match based on distance. This was the one we thought about converting to mysql.

2021-01-12 21:12 UTC, MarcusEbert requested changes

2021-01-12 21:12 UTC, MarcusEbert commented on shoal-server/shoal_server/utilities.py
>  GEODOMAIN_DB = os.path.join(config.geodomain_path, "GeoIP2-Domain.mmdb")
I believe the domain db is no longer used and replaced by the dig calls to determine the domain of an IP.

2021-01-13 22:44 UTC, MCatherine1994 commented on shoal-server/conf/shoal_wsgi.py
> +import logging
This file appears at two locations, "shoal/shoal-server/scripts/shoal_wsgi.py" and "shoal/shoal-server/conf/scripts/shoal_wsgi.py" and have the same content. In the setup file, it includes "conf/scripts/shoal_wsgi.py", and I didn't see any usage of the other one.

2021-01-13 22:46 UTC, MCatherine1994 commented on shoal-server/setup.py
> +                       ('share/shoal-server/scripts', ['conf/scripts/shoal_wsgi.py']),
This is where the shoal_wsgi.py has been included. Didn't see the other shoal_wsgi.py file has been used anywhere

2021-01-13 23:25 UTC, MCatherine1994 commented on shoal-server/shoal_server/config.py
> +import configparser
we only confirmed the support of python3 for shoal-server

2021-01-13 23:27 UTC, MCatherine1994 commented on shoal-server/shoal_server/utilities.py
> +level = logging.getLevelName(config.logging_level)
tested and updated

2021-01-13 23:27 UTC, MCatherine1994 commented on shoal-server/shoal_server/utilities.py
>  GEODOMAIN_DB = os.path.join(config.geodomain_path, "GeoIP2-Domain.mmdb")
removed

2021-01-14 00:08 UTC, MCatherine1994 commented on shoal-server/shoal_server/utilities.py
>          else:
Removed the if-else condition to check squid.global_acess, as this value is initialized as false, and will only become true when it passes the verification tests. So when at this step, its value is always false. Updated the to just have squid.error = "%s/%s URLs have proxy errors and %s/%s URLs are unreachable. Squid is configured for Local Access Only. Cannot verify %s" % (badpaths, len(paths), badflags, len(paths), hostname)"

2021-01-18 20:33 UTC, colsond requested changes

2021-01-18 20:33 UTC, colsond commented on shoal-server/shoal_server/config.py
>  elif exists(abspath(homedir + "/.shoal/shoal_server.conf")):
For the server all config file locations can be removed except for the one in /etc/shoal/

2021-01-29 19:43 UTC, MarcusEbert approved these changes

2021-02-23 19:06 UTC, colsond approved these changes

2021-02-23 19:06 UTC, merged