Merge: merge agent-python3 to master for version 0.10.0
hep-gc/shoal pull request #159
Opened 2021-01-04 23:11 UTC by MCatherine1994

- Updated to support both python2 and python3
- Added broadcast functionality
- Added auto configuration of the ips, port number, etc... and removed the setting of global/domain access
- Added simple functional test for the running squid
- Added email notification for the unavailable squid
- Added readme to pypi project description
- Updated version to 0.10.0

2021-01-08 23:05 UTC, colsond requested changes

2021-01-08 23:05 UTC, colsond commented on shoal-agent/shoal_agent/config.py
> +email_content = 'Hello, there is no available squid running on the agent, please review the squid status. Squid will be retried in 30 mins. Thanks!'
It may be nice to provide some details along with the email if we can- we can discuss with marcus what would be appropriate.

2021-01-08 23:05 UTC, colsond commented on shoal-agent/shoal_agent/config.py
> +# get max_load
Just thinking here that if there are squids that serve both on private and public networks using only 1 link may not paint an accurate picture of the system load.

2021-01-11 18:11 UTC, MarcusEbert requested changes

2021-01-11 18:18 UTC, colsond commented on shoal-agent/shoal-agent
> +    MAGIC = "fna349fn" #to make sure we don't confuse or get confused by other programs
Rename MAGIC to something readable like broadcast_id.

2021-01-11 18:43 UTC, colsond requested changes

2021-01-11 18:43 UTC, colsond commented on shoal-agent/README.md
> +  4. Move configuration files from `/shoal-agent/conf/` to their proper locations:
Remove git install instructions (pip only)

2021-01-11 18:43 UTC, colsond commented on shoal-agent/shoal_agent/config.py
> +    print("Couldn't auto config the squid port, use the default one")
add the default variable to show port (%s % squid_port)

Move default port definition to config file- only use it if port cant be determined programmatically. 

Set squid port to config value in except block

2021-01-11 18:43 UTC, colsond commented on shoal-agent/shoal_agent/config.py
> +# get max_load
This problem is quite complicated and should probably be considered as a major feature of a future shoal release. (make an issue)

2021-01-14 22:37 UTC, MCatherine1994 commented on shoal-agent/shoal_agent/config.py
>  homedir = expanduser('~')
used when find the config file, updated that order to be: run location > homedir > /etc/shoal

2021-01-21 00:18 UTC, MCatherine1994 commented
Installation Requirements:
- Packages for python2: epel-release (for python-pip), python-pip, python-netifaces, python-pika
- Packages for python3: python3, python3-pip
- Make a directory /etc/shoal/, and a directory /etc/sysconfig/shoal/, copy config files to proper locations
- Create user and group shoal
- Create a file /var/log/shoal_agent.log, change the owner to shoal

Todo: discuss the location of config files, whether install them directly to the proper location or install them at one location and let the user copy them to the proper place

2021-01-21 19:18 UTC, colsond commented
remove sysconfig file (and references in init//service files)
Change init//service file user to shoal.
Post install script to:
 -create/change owner of log file
 -conditionally copy config file
 -copy all data files to proper locations (currently using setup.py's data_files)
 start service

2021-01-29 00:28 UTC, MCatherine1994 commented
python2 will install shoal-agent-installation command to /usr/bin/shoal-agent-installation
python3 will install shoal-agent-installation command to /usr/local/bin/shoal-agent-installation, and to run this command, need to use "sudo su -"

also found that in setup.py file, data_file option we set the destination to be "share/shoal-agent", this is different in python2 and python3 when using pip install. For python2, our config files will be placed at "/usr/share/shoal-agent/", but for python3, they will be at "/usr/local/share/shoal-agent/". (As run "setup.py install" won't do anything about the data_file option, I didn't notice this at the beginning)

2021-01-29 17:26 UTC, MarcusEbert commented
It should be possible to force a specific install dir for both version of python by using the "--prefix" option of pip, e.g. 
"--prefix=/usr" should install in /usr/bin/
"--prefix=/usr/local" should install in /usr/local/bin/

2021-01-29 18:17 UTC, MCatherine1994 commented
- config file path
- where to put config files /usr/share/ /usr/local/share
- how to write new config file, replace some value or write entire new one
- how user will run shoal-agent-installation command, sudo su -

2021-02-03 17:59 UTC, MarcusEbert commented on shoal-agent/README.md
> +  2. With python version 2+, run the installation script `sudo shoal-agent-installation`, and set your config options with the installation script; With python version 3+, first run as root `sudo su
Schript should end with ".sh" 
Better use the same approach for both, maybe:
1. Login as root or become root via "sudo su -" 
2. Install shoal-agent using pip/pip3, e.g. "pip3 install shoal-agent"
3. Run the installation script, shoal-agent-installation.sh, to setup your configuration

2021-02-03 18:07 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation
> +SERVICE_STATUS=$(systemctl is-active shoal-agent)
I want to check if the shoal-agent is running or not before let the service stop, shall I do it this way? Otherwise, it might show like "fail: units not loaded"

2021-02-03 18:09 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation
> +useradd shoal -g shoal
If the user exists, it will show "user already exists", I don't think it's a big problem, but just want to mention it here.

2021-02-03 18:11 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation
> +SERVICE_STATUS=$(systemctl is-active shoal-agent)
"sytemctl" doesn't work on an init.d system. 
How about: "service shoal-agent stop 2>/dev/null"  ?

2021-02-03 18:11 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation
> +useradd shoal -g shoal
Send output to /dev/null if we don't want to have it displayed.

2021-02-03 18:13 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation
> +echo Reloaded units for shoal-agent.service
When we put a new service file to replace the old one (at line 46), it will show a Warning message "service file changed, run systemctl daemon-reload to reload". So I added this print statement here to show the user we already reload the units for the service file, they don't need to worry about that.

2021-02-03 18:20 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation
> +echo Reloaded units for shoal-agent.service
In general, I think we should redirect all system command outputs that we don't need to /dev/null and then, if needed, use our own "echo" statements to give information to the user

2021-02-03 18:21 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation
> +echo Reloaded units for shoal-agent.service
It will also result in an error on an init.d system...

2021-02-03 22:09 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +    OLD_CFG_CONTENT=$(grep -v "^#\|\[" $CONFIG_FILE|sed -r 's/\s+=\s/=/g')
Added "sed -r 's/\s+=\s/=/g'" to remove spaces around "=" sign for valid variable assignment. In our new shoal_agent.conf file, I removed all spaces around "=", but in case the user's old config file still has spaces around "=", added this command here. Bash shell could only read the variable value in the format of "a=1" (could read by $a), not "a = 1".

2021-02-03 22:20 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation.sh
> +    OLD_CFG_CONTENT=$(grep -v "^#\|\[" $CONFIG_FILE|sed -r 's/\s+=\s/=/g')
Ah, I see. True, for bash you should not have spaced around the "=" if you want to eval it

2021-02-03 22:33 UTC, MarcusEbert reviewed
I think it would be best to change the way the bash functions work so they do not use anything outside of the function body.

2021-02-03 22:33 UTC, MarcusEbert commented on shoal-agent/README.md
>  ### Recommended Method: Use pip (est. ~5 min)
Nice how short the instructions are now!

2021-02-03 22:33 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation.sh
> +compareVersion() {
Personally, I prefer when functions only work on their own (local) variables and get as an option all information they need to work but not depend on or modify global variables. They should return something useful for the purpose of what they do.

2021-02-03 22:33 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation.sh
> +setNewValues() {
see above comment about functions

2021-02-04 00:10 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +setNewValues() {
In this function, here we are using more than 10 variables, if we all use local variables, then when we calling this function, we need to give more than 10 parameters, is there a better way to pass these parameters?

2021-02-04 00:36 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation.sh
> +setNewValues() {
Why not remove this function and move the content to the main part of the program where currently "setNewValues" is called?

2021-02-04 01:13 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +compareVersion() {
updated

2021-02-04 01:14 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +setNewValues() {
yeah, previously thought to write a function could save some duplicate code, but then it will have too many parameters, I updated to use the content in the function directly in the main part of the program

2021-02-04 23:16 UTC, MarcusEbert approved these changes
Looks good; we can talk about the 2 comments I left.  
I think for a merge it is ok like it is, additional changes can also be done before a new release is made once it is in the master-branch.

2021-02-04 23:16 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation.sh
> +setEachNewValue admin_email "admin email is used for contact in case of issues with the shoal-agent or squid" root@localhost
Should we have an old value also for the admin email?

2021-02-04 23:16 UTC, MarcusEbert commented on shoal-agent/shoal_agent/config.py
> +receiver_email = 'root@localhost'
Shouldn't this be taken from the config instead of be hard-coded?

2021-02-04 23:29 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +setEachNewValue admin_email "admin email is used for contact in case of issues with the shoal-agent or squid" root@localhost
yeah, we could, currently there is no admin email from an old config file, but in the future we should have it

2021-02-04 23:30 UTC, MCatherine1994 commented on shoal-agent/shoal_agent/config.py
> +receiver_email = 'root@localhost'
I think at the end of this file, it rewrites this receiver_email if there is an admin_email in the config file.

2021-02-04 23:46 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +setEachNewValue admin_email "admin email is used for contact in case of issues with the shoal-agent or squid" root@localhost
updated

2021-02-05 17:55 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +    OLD_INTERVAL=$interval
Hi @MarcusEbert, I have a question here. If there is no "interval" defined in the old config file, the $interval here should be empty. But in fact, as these variable names are the same for the old config file and our new config file, if "interval" is not in the old config file, its value won't be rewritten, and it will still be the value we read before (when setting the default value) from the new config file 30. 

But in theory, the user's existing config file should have all these variables, the only new variable here is the admin_email, but this one we didn't read from the new config file, I hardcoded it before, this one is fine. All others should exist in the existing config file, it shouldn't be a big problem, do you think I better reset these values to empty before re-read from the old config file?

2021-02-05 20:20 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation.sh
> +    OLD_INTERVAL=$interval
True. Also in general we don't need to have $interval set to anything at this point, right?  All we care about here is $OLD_INTERVAL and $DEFAULT_INTERVAL (and similar for all variables).
What could help is to remove the "eval", here and for $DEFAULT_* and have a case construct instead where you set the OLD_* (or DEFAULT_*) variables. In that case you also don't have to worry about spaces around "=" and can process the output directly instead of putting it into the CONTENT variable.

2021-02-05 21:05 UTC, MarcusEbert commented on shoal-agent/shoal-agent-installation.sh
> +compareVersion() {
I would reorder the code in a way that 
* all global variables are at the top 
* all functions are after the definition of the global variables
* code outside of functions comes after the definition of all functions

2021-02-05 23:14 UTC, MCatherine1994 commented on shoal-agent/shoal-agent-installation.sh
> +compareVersion() {
Updated

2021-02-06 02:30 UTC, MarcusEbert reviewed
Looks good to me now. Small changes that come up later can also be done after the merge to the master branch. @colsond are there any outstanding issues or can me merge this to the master branch?

2021-02-09 21:37 UTC, colsond approved these changes
Code looks good, only thing i see outstanding is a few print statements that could be log statements but they are not critical.

2021-02-09 21:37 UTC, colsond commented on shoal-agent/shoal-agent
> +    print("starting shoal-agent broadcast thread")
These should still be updated to output to the logfile instead of stdout.

2021-02-09 21:37 UTC, merged

2021-02-09 23:51 UTC, MCatherine1994 commented on shoal-agent/shoal_agent/__version__.py
> +version = "0.10.0"
I think in the latest code, this version is set to 1.0.0

2021-02-10 19:19 UTC, MCatherine1994 commented on shoal-agent/setup.py
>        packages=['shoal_agent'],
not sure if I understand correctly, but for data files, we couldn't copy config files to /etc/ or /usr/lib directly, for example:
data_files=[('/etc/shoal', ['conf/shoal_agent.conf'])]
This not works, as when doing pip install, the path here is relative, shoal_agent.conf will be installed at '/usr/etc/shoal/shoal_agent.conf', where '/usr' is the system prefix,  not '/etc/shoal/'. So we keep config files all at 'share/shoal' when install, and created the installation script to copy them to proper places.