Merge: merge client-python3 to master for version 0.6.6
hep-gc/shoal pull request #160
Opened 2021-01-05 00:20 UTC by MCatherine1994

Summary of changes on shoal-client:
- Updated to support both python2 and python3
- Updated get extra verified squids from the shoal-server
- Added functional test for squids returned from shoal-server, and rank squids based on the time cost
- Removed the duplicate squids
- Added readme to pypi project description
- Updated version to 0.6.6

2021-01-07 17:06 UTC, colsond commented on shoal-client/setup.py
>        author='Mike Chester, Colson Drimiel, Ian Gable, Alex Lam, Rob Prior, Ryan Taylor, Steve Traylen',
add Cathrine and Marcus as authors

2021-01-07 17:07 UTC, colsond commented on shoal-client/setup.py
>        author_email='igable@uvic.ca',
update email to group email (heprc@uvic.ca ??)

2021-01-07 17:08 UTC, colsond commented on shoal-client/setup.py
> +          'requests>=2.6.0',
add netifaces

2021-01-07 17:12 UTC, colsond commented on shoal-client/shoal-client
>      while 1:
remove while loop

2021-01-07 17:13 UTC, colsond commented on shoal-client/shoal-client
> +        dump = True
no dump unless dump flag set

2021-01-07 17:27 UTC, rseuster commented on shoal-client/shoal-client
>      while 1:
For reasons I forgot (should have made a comment !) the while look was required in this place. See the "break" statements later. You should test carefully that this still works.

2021-01-07 17:33 UTC, colsond commented on shoal-client/shoal-client
>      while 1:
The break statements can be removed along with the while. The way this loop is structured it will never run the loop more than once anyways.

2021-01-07 17:37 UTC, colsond commented on shoal-client/shoal-client
> +        syslog.syslog(syslog.LOG_ERR, "Unable to detect the local ip address")
update comment detect -> check

2021-01-07 17:45 UTC, rseuster commented
Can you have an empty exception ? Or would a "pass" go there ? Thought I 
tried that.

On 2021-01-07 9:33 a.m., Colson Driemel wrote:
>
> *@colsond* commented on this pull request.
>
> ------------------------------------------------------------------------
>
> In shoal-client/shoal-client 
> <https://github.com/hep-gc/shoal/pull/160#discussion_r553476828>:
>
> >      PORT = 50000
>       MAGIC = "fna349fn" #to make sure we don't confuse or get confused by other programs
>   
>       from socket import socket, AF_INET, SOCK_DGRAM
>       
>       s = socket(AF_INET, SOCK_DGRAM) #create UDP socket
>       s.bind(('', PORT))
> -    s.settimeout(90)
> +    s.settimeout(t)
>       
>       while 1:
>
> The break statements can be removed along with the while. The way this 
> loop is structured it will never run the loop more than once anyways.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/hep-gc/shoal/pull/160#discussion_r553476828>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AEAHI7TAWMVWSLGGIYRSOJTSYXV7VANCNFSM4VT3RLXQ>.
>

2021-01-07 18:32 UTC, rseuster commented on shoal-client/shoal-client
>      while 1:
Can you have an empty exception ? Or would a "pass" go there ? Thought I tried that.

2021-01-07 19:52 UTC, colsond requested changes

2021-01-07 19:52 UTC, colsond commented on shoal-client/shoal-client
> +        if (same_subnet or not my_ip) and functionalTest(private_ip, port):
instead of using "not my_ip" if we are unable to figure out the clients private ip set a variable client_priv_ip_not_found to use for this if statement.

2021-01-07 19:52 UTC, colsond commented on shoal-client/shoal-client
> +                        timer = time.time() - start_time
This method of timing will include the error time for any IPs that fail. TO get a more accurate time we should only time the functional test and only use the time if the test succeeds.

2021-01-07 19:52 UTC, colsond commented on shoal-client/shoal-client
> +        if len(avaliable_server_return.keys()) > 0:
The above has a lot of code duplication, and can be condensed to use the same code and then a function call at the end to format the string appropriately (frontier vs regular)

2021-01-11 17:56 UTC, MarcusEbert requested changes

2021-01-11 17:56 UTC, MarcusEbert commented on shoal-client/setup.py
> +        print("Couldn't use either setuputils or distutils. Install one of those.")
change "setuputils" to "setuptools"

2021-01-11 17:56 UTC, MarcusEbert commented on shoal-client/shoal-client
> +        syslog.syslog(syslog.LOG_ERR, "Unable to check the local ip address")
change to "Unable to use a private IP address."

2021-01-11 17:56 UTC, MarcusEbert commented on shoal-client/shoal-client
> +    f = opener.open(server_url, timeout=5)
Isn't timeout=2 used elsewhere for testing? If so, why 5s here instead?

2021-01-11 17:56 UTC, MarcusEbert commented on shoal-client/shoal-client
>  if not no_shoal_server:
is "no_shoal_server" still tested earlier in the code?

2021-01-11 17:56 UTC, MarcusEbert commented on shoal-client/shoal-client
> +                closest_http_proxy += '(proxyurl=http://%s:%s)' % (item[1][0], item[1][1])
"closest" may not be true since we test only return time but not the geographic distance.

2021-01-11 17:56 UTC, MarcusEbert commented on shoal-client/shoal_client/config.py
>  elif exists(abspath(homedir + "/.shoal/shoal_client.conf")):
Do we want to keep this chain of possible conf file location or force to have only a single one?

2021-01-11 19:22 UTC, colsond requested changes

2021-01-11 19:22 UTC, colsond commented on shoal-client/shoal-client
>  if not no_shoal_server:
We need to consider consolidating these 2 code blocks.
Either
a) we combine this if else and handle the case where we are unable to contact the shoal server by formatting the strings without server results, or;
b) we update the else block to include the broadcast squid.

a) is probably preferable since it will reduce any code duplication and stop us from forgetting to update both blocks of code any time we make changes.

2021-01-11 19:22 UTC, colsond commented on shoal-client/shoal-client
> +                if frontier:
No need for this print, maybe downgrade it to a logging debug or remove completely

2021-01-11 19:22 UTC, colsond commented on shoal-client/shoal-client
> +                closest_http_proxy += '(proxyurl=http://%s:%s)' % (item[1][0], item[1][1])
Not a critical change but "best_http_proxy" would now be a more accurate name.

2021-01-11 19:22 UTC, colsond commented on shoal-client/shoal_client/config.py
>  elif exists(abspath(homedir + "/.shoal/shoal_client.conf")):
precedence:
run location > homedir > /etc/shoal

2021-01-14 19:59 UTC, MCatherine1994 commented on shoal-client/setup.py
>        author_email='igable@uvic.ca',
will sign up a role-based email as the author email

2021-01-14 20:04 UTC, MCatherine1994 commented on shoal-client/shoal-client
>      while 1:
Removed while loop, added "syslog.syslog(syslog.LOG_ERR, "Socket got a timeout")" to the exception block

2021-01-14 20:09 UTC, MCatherine1994 commented on shoal-client/shoal-client
> +    BROADCAST_ID = "fna349fn" #to make sure we don't confuse or get confused by other programs
Update the "MAGIC" variable name to be "BROADCAST_ID", more clear and matches the same variable name in shoal-agent

2021-01-14 20:20 UTC, MCatherine1994 commented on shoal-client/shoal-client
> +                if frontier:
removed

2021-01-14 20:22 UTC, MCatherine1994 commented on shoal-client/shoal-client
>  if not no_shoal_server:
Removed the usage of variable "no_shoal_server", updated the if-else statement at the end of the file, removed the duplicate code

2021-01-14 20:24 UTC, MCatherine1994 commented on shoal-client/shoal-client
> +else:
wondering when will we get to this else condition, if not dump and not the frontier, maybe when using "-n"?

2021-01-18 19:48 UTC, colsond commented on shoal-client/setup.py
>        author_email='igable@uvic.ca',
new role based email: heprc-shoal@uvic.ca

2021-01-18 19:56 UTC, colsond commented on shoal-client/shoal-client
> +else:
This block is were the code ends up if shoal is operating normally. If you are not testing with --dump or requesting a frontier specific string this code below executes the cvmfs_talk command to update the proxy string.

2021-01-21 00:11 UTC, MCatherine1994 commented
Installation requirements:
- Packages for python2：epel-release (for python-pip), python-pip, python-netifaces (needed for error: Setup script exited with error: command 'gcc' failed with exit status 1); 
- Packages for python3: python3, python3-pip
- Make a directory /etc/shoal/, and copy config file shoal_client.conf to /etc/shoal/ (shoal_client.conf will be at /shoal/shoal-client/conf/shoal_client.conf if install using git method, and in /usr/share/shoal-client/shoal_client.conf if install using pip method)

2021-01-25 22:49 UTC, MCatherine1994 commented
shoal_client.conf will be placed under /etc/shoal/ if no config file exists there, otherwise will do nothing, still use the existing one in that directory. Mentioned in Readme that the latest config file is available in the git repo.

2021-02-10 00:59 UTC, MCatherine1994 commented on shoal-client/shoal_client/config.py
> +          "Please check configuration file:", path)
Should I better mention "please consider to add a default squid proxy" as well?

2021-02-10 22:03 UTC, colsond approved these changes
Code seems fine.

2021-02-10 22:03 UTC, colsond commented on shoal-client/README.md
>  4. Check settings in `shoal_client.conf` update as needed
got 2 step 4s here.

2021-02-10 23:15 UTC, MCatherine1994 commented on shoal-client/README.md
>  4. Check settings in `shoal_client.conf` update as needed
updated

2021-02-23 17:51 UTC, MCatherine1994 commented on shoal-client/shoal-client
> +            server_squids[squid['public_ip'] or squid['hostname']] = squid
The server_squids is used for default squids to compare with and remove the duplicate. If squid has a public ip, it will store the public ip, otherwise will try to store the hostname for later comparison. If we don't use hostname anywhere, maybe I could update it to private ip? 
Or maybe move this step a little down to after done the test, store the ips that pass the test? (this will consider private ip first and then public ip)

2021-02-23 20:24 UTC, MCatherine1994 commented on shoal-client/shoal-client
> +            server_squids[squid['public_ip'] or squid['hostname']] = squid
Updated, see commit b0a82be

2021-02-23 23:10 UTC, MarcusEbert approved these changes

2021-03-01 19:00 UTC, merged